/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NguoiDungBUS;
import BUS.SingletonBusUtil;
import BUSImpl.NguoiDungBUSImpl;
import Constant.Constant;
import DTO.NguoiDungDTO;
import DTO.PhongThiDTO;
import DTO.VaiTroDTO;
import Report.JasperRp;
import Report.UtilConnect;
import Table.SinhVienTable;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.ObjectNotFoundException;

/**
 *
 * @author hocgioinhatlop
 */
public class DanhSachPhongThi extends javax.swing.JDialog {

    SinhVienTable cod = new SinhVienTable();
    List<NguoiDungDTO> userDTOS = new ArrayList<NguoiDungDTO>();
    List<PhongThiDTO> listIdPhong;

    public DanhSachPhongThi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        paint_table();           
        setCbPhongThi();
        userDTOS= SingletonBusUtil.getPhongThiBUSInstance().findSinhVienByEqualUnique("maPhong", 1);
        
        cod.showTable((ArrayList<NguoiDungDTO>) userDTOS, table);

    }
    public void setCbPhongThi(){
        listIdPhong=SingletonBusUtil.getPhongThiBUSInstance().findListIdPhongThi();
       
        for(int i=0; i< listIdPhong.size(); i++){
            cbPhongThi.addItem(listIdPhong.get(i).getMaPhong().toString());
            
        }
        
    }

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonThem = new javax.swing.JButton();
        cbPhongThi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(602, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonXoa.setBackground(new java.awt.Color(93, 200, 119));
        buttonXoa.setForeground(new java.awt.Color(255, 255, 255));
        buttonXoa.setText("Xóa");
        buttonXoa.setContentAreaFilled(false);
        buttonXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXoa.setOpaque(true);
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 139, 31));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Danh sách phòng thi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, -1));

        jButton2.setBackground(new java.awt.Color(93, 200, 119));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xuất danh sách");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 151, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setFillsViewportHeight(true);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, 360));

        buttonThem.setBackground(new java.awt.Color(93, 200, 119));
        buttonThem.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem.setText("Thêm");
        buttonThem.setContentAreaFilled(false);
        buttonThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem.setOpaque(true);
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });
        jPanel1.add(buttonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 139, 30));

        cbPhongThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhongThiActionPerformed(evt);
            }
        });
        jPanel1.add(cbPhongThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 830, 470));

        setSize(new java.awt.Dimension(845, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        Object[] options = {"Xóa  ", "Thôi không xóa "};
        int n = JOptionPane.showOptionDialog(rootPane,
                "Chắc chắn muốn xóa ? ",
                "Question",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {
        
            SingletonBusUtil.getPhongThiBUSInstance().deleteDeThi(Integer.parseInt(cbPhongThi.getSelectedItem().toString()));
            cbPhongThi.removeItem(cbPhongThi.getSelectedItem());
            cbPhongThi.setSelectedIndex(0);
            userDTOS= SingletonBusUtil.getPhongThiBUSInstance().findSinhVienByEqualUnique("maPhong", Integer.parseInt(cbPhongThi.getSelectedItem().toString()));
            cod.showTable((ArrayList<NguoiDungDTO>) userDTOS, table);
            
        } else if (n == JOptionPane.NO_OPTION) {
            return;
        } else {
        }


    }//GEN-LAST:event_buttonXoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Connection conn;
        conn = UtilConnect.getConnection();
        try {
            JRTableModelDataSource dataSource= new JRTableModelDataSource(table.getModel());
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\hocgioinhatlop\\OneDrive\\Documents\\NetBeansProjects\\Thitracnghiem\\src\\Report\\report1.jrxml");
          
            JasperReport jsreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jsreport, null, dataSource);
            JasperViewer jv= new JasperViewer(jprint,false);
           JDialog dialog = new JDialog(this);//the owner
            dialog.setContentPane(jv.getContentPane());
            dialog.setSize(jv.getSize());
            dialog.setTitle("Danh sách");

            dialog.setVisible(true);
//            JasperViewer.viewReport(jprint);
//            JasperViewer.
        } catch (JRException ex) {
            Logger.getLogger(JasperRp.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained

    }//GEN-LAST:event_tableFocusGained

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased

    }//GEN-LAST:event_tableMouseReleased

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
           dispose();
        new SLThiSinh(this, true).setVisible(true);
       // setVisible(true);
      //listIdPhong=SingletonBusUtil.getPhongThiBUSInstance().findListIdPhongThi();
    //  cbPhongThi.addItem(listIdPhong.get(listIdPhong.size()-1).getMaPhong().toString());
      
       

    }//GEN-LAST:event_buttonThemActionPerformed

    private void cbPhongThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhongThiActionPerformed
       if(cbPhongThi.getSelectedItem() != null){
        Object maphong=Integer.parseInt(cbPhongThi.getSelectedItem().toString());
        userDTOS= SingletonBusUtil.getPhongThiBUSInstance().findSinhVienByEqualUnique("maPhong", maphong);
        cod.showTable((ArrayList<NguoiDungDTO>) userDTOS, table);
    }
    }//GEN-LAST:event_cbPhongThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DanhSachPhongThi dialog = new DanhSachPhongThi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JComboBox<String> cbPhongThi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
private void paint_table() {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(60, 127, 177));
        table.getTableHeader().setForeground(new Color(255, 255, 255));
        table.setRowHeight(30);
        table.setShowGrid(true); // de the hien duong vien mac dich
        //table.setShowHorizontalLines(true);// de the hien duong vien ngang
        //table.setShowVerticalLines(true);// de the hien duong vien doc

    }

}
