/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.SingletonBusUtil;
import DTO.NguoiDungDTO;
import Util.SessionUser;
import javax.swing.JOptionPane;

/**
 *
 * @author hocgioinhatlop
 */
public class DoiMatKhau1 extends javax.swing.JDialog {
    NguoiDungDTO user= new NguoiDungDTO();
    
    public DoiMatKhau1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_MatKhau2 = new javax.swing.JPasswordField();
        txt_MatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(195, 195, 195));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));

        jSeparator3.setForeground(new java.awt.Color(195, 195, 195));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, 10));

        jLabel3.setForeground(new java.awt.Color(91, 91, 91));
        jLabel3.setText("Nhập mật khẩu mới");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnLogin1.setBackground(new java.awt.Color(93, 200, 119));
        btnLogin1.setText("Đổi mật khẩu");
        btnLogin1.setContentAreaFilled(false);
        btnLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin1.setOpaque(true);
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, -1));

        jLabel4.setForeground(new java.awt.Color(91, 91, 91));
        jLabel4.setText("Mật khẩu mới:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 60, 48));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thay đổi mật khẩu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 30));

        txt_MatKhau2.setBorder(null);
        txt_MatKhau2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MatKhau2KeyReleased(evt);
            }
        });
        jPanel1.add(txt_MatKhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 240, 30));

        txt_MatKhau.setBorder(null);
        txt_MatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MatKhauKeyReleased(evt);
            }
        });
        jPanel1.add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        user=SingletonBusUtil.getNguoiDungBUSInstance().findById(Integer.parseInt(SessionUser.getMaNguoiDung()));
        String matkhau=txt_MatKhau.getText();
        String xacNhanMK=txt_MatKhau2.getText();
        if(matkhau.equals(xacNhanMK))
        {
            user.setMatKhau(matkhau);
            SingletonBusUtil.getNguoiDungBUSInstance().updateUser(user);
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại thông tin");
        }

    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void txt_MatKhau2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhau2KeyReleased

    }//GEN-LAST:event_txt_MatKhau2KeyReleased

    private void txt_MatKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhau1 dialog = new DoiMatKhau1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txt_MatKhau;
    private javax.swing.JPasswordField txt_MatKhau2;
    // End of variables declaration//GEN-END:variables
}
