/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChuongMonHocBUS;
import BUS.MonHocBUS;
import BUS.SingletonBusUtil;
import BUSImpl.ChuongMonHocBUSImpl;
import BUSImpl.MonHocBUSImpl;
import DAO.ChuongMonHocDAO;
import DAO.MonHocDAO;
import DAOImpl.ChuongMonHocDAOImpl;
import DAOImpl.MonHocDAOImpl;
import DTO.ChuongMonHocDTO;
import DTO.MonHocDTO;
import Entity.ChuongMonHocEntity;
import Entity.MonHocEntity;
import Util.ChuongMonHocBeanUtil;
import Util.MonHocBeanUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.exception.ConstraintViolationException;

/**
 *
 * @author hocgioinhatlop
 */
public class QLChuongMonHoc extends javax.swing.JDialog {

    /**
     * Creates new form QLChuongMonHoc
     */
    private List<ChuongMonHocDTO> list;
     DefaultTableModel model;
     
    public QLChuongMonHoc(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setCbSubject();
        model = (DefaultTableModel) jTable1.getModel();
     //   addTable();
        
    }
    public void setCbSubject(){
        List <MonHocDTO> listSubjectName=SingletonBusUtil.getMonHocBUSInstance().findAll();
       
        for(int i=0; i< listSubjectName.size(); i++){
            cbSubject.addItem(listSubjectName.get(i).getTenMonHoc());
            
        }
        
    }
     public void addTable(){                
        model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{
            "Mã chủ đề", "Tên chủ đề", "Môn học","Số tiết"
        });
        
        for(ChuongMonHocDTO tp : list){
            model.addRow(new Object[]{
                tp.getMaChuong(),tp.getTenChuong(),tp.getMonHocDTO().getTenMonHoc(),tp.getSoTiet()
            });
        }
    }
     private void showResult(){
        
        ChuongMonHocDTO topic = list.get(list.size() - 1);
        model.addRow(new Object[]{ topic.getMaChuong(), topic.getTenChuong(), cbSubject.getSelectedItem(),topic.getSoTiet()});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        txTopicName = new javax.swing.JTextField();
        btXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txTopicID = new javax.swing.JTextField();
        cbSubject = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txSoTiet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Môn học : ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nhập Chương ");

        jLabel2.setText("Tên chương :");

        btThem.setText("Thêm ");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        txTopicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTopicNameActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chủ đề", "Tên chủ đề ", "Môn học "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Danh Sách Chủ Đề");

        jLabel5.setText("Mã chương:");

        cbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectActionPerformed(evt);
            }
        });

        jLabel6.setText("Số tiết :");

        txSoTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSoTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btThem, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btXoa, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txTopicID))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txTopicID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txSoTiet)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoa)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(831, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
       
        if(txTopicID.getText().equals("")|| txTopicName.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng kiểm tra lại thông tin !!!");
            return;
        }
            
        ChuongMonHocDTO dto= new ChuongMonHocDTO();
        dto.setMaChuong(Integer.parseInt(txTopicID.getText()));
        dto.setTenChuong(txTopicName.getText());
        dto.setSoTiet(Integer.parseInt(txSoTiet.getText()));
        Object selected = cbSubject.getSelectedItem();
        String subjectName = selected.toString();
                          
        List <MonHocDTO> listSubjectName=SingletonBusUtil.getMonHocBUSInstance().findAll();
       
        int id = 0;
        for (MonHocDTO sj: listSubjectName){
            if(sj.getTenMonHoc().equals(subjectName)){
            id = sj.getMaMonHoc();
            
            }
        }
        int subjectID = id;
        MonHocDTO monhoc=new MonHocDTO();
        monhoc.setMaMonHoc(id);
        dto.setMonHocDTO(monhoc);
        
          try{      
        SingletonBusUtil.getChuongMonHocBUSInstance().saveChuongMonHoc(dto);       
        list.add(dto);
        showResult();
        JOptionPane.showMessageDialog(rootPane, "Thêm chương môn học thành công !");
          }catch(ConstraintViolationException e){
              JOptionPane.showMessageDialog(rootPane, "Thêm chương môn học thất bại vui lòng kiểm tra lại mã môn học!");
          }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btThemActionPerformed

    private void txTopicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTopicNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTopicNameActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        Object[] options = {"Xóa  ", "Thôi không xóa "};
        int n = JOptionPane.showOptionDialog(rootPane,
            "Chắc chắn muốn xóa ? ",
            "Question",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);
        if (n == JOptionPane.YES_OPTION) {
            //
            try{
                int SelectRow = jTable1.getSelectedRow();
                int id = Integer.parseInt(model.getValueAt(SelectRow, 0).toString()) ;
                
                SingletonBusUtil.getChuongMonHocBUSInstance().deleteChuongMonHoc(id);
                model.removeRow(SelectRow);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Xóa không thành công !");
            }
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công !");
            //
        } else if (n == JOptionPane.NO_OPTION) {
            return;
        } else {
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int SelectRow = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        //  int ID = Integer.parseInt(model.getValueAt(SelectRow, 0).toString()) ;
        txTopicID.setText(model.getValueAt(SelectRow, 0).toString());
        txTopicName.setText(model.getValueAt(SelectRow, 1).toString());
        txSoTiet.setText(model.getValueAt(SelectRow, 2).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void cbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectActionPerformed
       String tenMH=cbSubject.getSelectedItem().toString();
       List <MonHocDTO> listSubjectName=SingletonBusUtil.getMonHocBUSInstance().findAll();
       
        int id = 0;
        for (MonHocDTO sj: listSubjectName){
            if(sj.getTenMonHoc().equals(tenMH)){
            id = sj.getMaMonHoc();           
            }
        }
        list=new ArrayList<ChuongMonHocDTO>();
     list= SingletonBusUtil.getChuongMonHocBUSInstance().findByMonHoc(id);
     addTable();
             
    }//GEN-LAST:event_cbSubjectActionPerformed

    private void txSoTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSoTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSoTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLChuongMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLChuongMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLChuongMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLChuongMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLChuongMonHoc dialog = new QLChuongMonHoc(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txSoTiet;
    private javax.swing.JTextField txTopicID;
    private javax.swing.JTextField txTopicName;
    // End of variables declaration//GEN-END:variables
}
