/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NguoiDungBUS;
import BUS.SingletonBusUtil;
import BUSImpl.NguoiDungBUSImpl;
import Constant.Constant;
import DTO.NguoiDungDTO;
import DTO.VaiTroDTO;
import Report.JasperRp;
import Report.UtilConnect;
import Table.SinhVienTable;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.ObjectNotFoundException;

/**
 *
 * @author hocgioinhatlop
 */
public class QLSinhVien extends javax.swing.JDialog {

    SinhVienTable cod = new SinhVienTable();
    ArrayList<NguoiDungDTO> userDTOS = new ArrayList<NguoiDungDTO>();

    public QLSinhVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        paint_table();
        Object[] objects = SingletonBusUtil.getNguoiDungBUSInstance().findByProperty(null, null, Constant.SORT_ASC, null, null, "");
        userDTOS = (ArrayList<NguoiDungDTO>) objects[1];
        cod.showTable(userDTOS, table);

    }

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonThem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfIdStu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNameStu = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbSapXep = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbChieuSapXep = new javax.swing.JComboBox<>();
        buttonXoa1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateNgaySinh1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateNgaySinh2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(602, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonXoa.setBackground(new java.awt.Color(93, 200, 119));
        buttonXoa.setForeground(new java.awt.Color(255, 255, 255));
        buttonXoa.setText("Xóa");
        buttonXoa.setContentAreaFilled(false);
        buttonXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXoa.setOpaque(true);
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 139, 31));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Danh sách sinh viên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, -1));

        jButton1.setBackground(new java.awt.Color(93, 200, 119));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm ");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Xuất thống kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 151, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setFillsViewportHeight(true);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 810, 240));

        buttonThem.setBackground(new java.awt.Color(93, 200, 119));
        buttonThem.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem.setText("Thêm");
        buttonThem.setContentAreaFilled(false);
        buttonThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem.setOpaque(true);
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });
        jPanel1.add(buttonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 139, 30));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm nâng cao"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Giới tính");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        tfIdStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdStuActionPerformed(evt);
            }
        });
        jPanel2.add(tfIdStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, 20));

        jLabel5.setText("Tìm theo tên sinh viên");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 150, 20));
        jPanel2.add(tfNameStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 170, 20));

        cbGioiTinh.setBackground(new java.awt.Color(250, 250, 250));
        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Nam", "Nữ" }));
        cbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhActionPerformed(evt);
            }
        });
        jPanel2.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel7.setText("Tìm theo ngày sinh");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 20));

        jLabel8.setText("Sắp xếp theo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 20));

        cbSapXep.setBackground(new java.awt.Color(250, 250, 250));
        cbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Mã người dùng", "Tên đăng nhập", "Ngày tạo", "Họ", "Tên", "Ngày sinh" }));
        cbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapXepActionPerformed(evt);
            }
        });
        jPanel2.add(cbSapXep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel9.setText("Chiều sắp xếp");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 70, 20));

        cbChieuSapXep.setBackground(new java.awt.Color(250, 250, 250));
        cbChieuSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Tăng dần", "Giảm dần" }));
        cbChieuSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChieuSapXepActionPerformed(evt);
            }
        });
        jPanel2.add(cbChieuSapXep, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        buttonXoa1.setBackground(new java.awt.Color(93, 200, 119));
        buttonXoa1.setForeground(new java.awt.Color(255, 255, 255));
        buttonXoa1.setText("Xóa");
        buttonXoa1.setContentAreaFilled(false);
        buttonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXoa1.setOpaque(true);
        buttonXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoa1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 139, 31));

        jButton3.setText("Mặc định");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));
        jPanel2.add(jDateNgaySinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, 20));

        jLabel10.setText("Tìm theo mã sinh viên");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        jLabel11.setText("Đến ngày");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 20));
        jPanel2.add(jDateNgaySinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 770, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 830, 470));

        setSize(new java.awt.Dimension(845, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        Object[] options = {"Xóa  ", "Thôi không xóa "};
        int n = JOptionPane.showOptionDialog(rootPane,
                "Chắc chắn muốn xóa ? ",
                "Question",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {
            int[] cacLuaChon = table.getSelectedRows();
            List<Integer> ids = new ArrayList<Integer>();
            for (int i = 0; i < cacLuaChon.length; i++) {
                ids.add(userDTOS.get(cacLuaChon[i]).getMaNguoiDung());

            }
            Integer checkDelete = SingletonBusUtil.getNguoiDungBUSInstance().deleteUsers(ids);
            if (checkDelete == ids.size()) {
                Object[] objects = SingletonBusUtil.getNguoiDungBUSInstance().findByProperty(null, null, Constant.SORT_ASC, null, null, "");
                userDTOS = (ArrayList<NguoiDungDTO>) objects[1];
                cod.showTable(userDTOS, table);
                JOptionPane.showMessageDialog(rootPane, "Xoá thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xoá thất bại");
            }

            //
        } else if (n == JOptionPane.NO_OPTION) {
            return;
        } else {
        }


    }//GEN-LAST:event_buttonXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Map<String, Object> property = new HashMap<String, Object>();
        String tuNgay = null;
        String denNgay = null;
        String whereClause = "";
        if (jDateNgaySinh1.getDate() != null) {
            tuNgay = convertJavaDateToSqlDate(jDateNgaySinh1.getDate()).toString();
            if (jDateNgaySinh2.getDate() != null) {
                denNgay = convertJavaDateToSqlDate(jDateNgaySinh2.getDate()).toString();
                whereClause = "AND ngaysinh BETWEEN '" + tuNgay + "' AND '" + denNgay + "'";
            } else {
                property.put("ngaySinh", tuNgay);
            }

        }

        if (!"".equals(tfIdStu.getText())) {
            try {
                NguoiDungDTO temp = SingletonBusUtil.getNguoiDungBUSInstance().findById(Integer.parseInt(tfIdStu.getText()));
                userDTOS = new ArrayList<NguoiDungDTO>();
                if (temp != null) {
                    userDTOS.add(temp);
                }
                cod.showTable(userDTOS, table);
            } catch (ObjectNotFoundException e) {
                userDTOS = new ArrayList<NguoiDungDTO>();
                cod.showTable(userDTOS, table);
            }

            return;
        }
        if (!"".equals(tfNameStu.getText())) {
            property.put("tenDayDu", tfNameStu.getText());

        }
        String sapXepTheo = null;
        if (!"None".equals(cbSapXep.getSelectedItem().toString())) {
//            None
//Mã người dùng
//Tên đăng nhập
//Ngày tạo
//Họ
//Tên
//Ngày sinh
            int temp = cbSapXep.getSelectedIndex();
            switch (temp) {
                case 1:
                    sapXepTheo = "maNguoiDung";
                    break;
                case 2:
                    sapXepTheo = "tenDangNhap";
                    break;
                case 3:
                    sapXepTheo = "ngayTao";
                    break;
                case 4:
                    sapXepTheo = "ho";
                    break;
                case 5:
                    sapXepTheo = "ten";
                    break;
                case 6:
                    sapXepTheo = "ngaySinh";
                    break;
                default:
                    sapXepTheo = null;
                    break;
            }

        }

        if (!"None".equals(cbGioiTinh.getSelectedItem().toString())) {
            property.put("gioiTinh", cbGioiTinh.getSelectedItem().toString());
        }
        String chieuSapXep = "1";
        if (!"None".equals(cbChieuSapXep.getSelectedItem().toString())) {
            chieuSapXep = Integer.toString(cbChieuSapXep.getSelectedIndex());
        }
        Object[] objects = SingletonBusUtil.getNguoiDungBUSInstance().findByProperty(property, sapXepTheo, chieuSapXep, null, null, whereClause);
        userDTOS = (ArrayList<NguoiDungDTO>) objects[1];
        cod.showTable(userDTOS, table);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Connection conn;
        conn = UtilConnect.getConnection();
        try {

            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\hocgioinhatlop\\OneDrive\\Documents\\NetBeansProjects\\Thitracnghiem\\src\\Report\\sinhvien.jrxml");
            String query = "select * from nguoidung where mavaitro=1";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesign.setQuery(updateQuery);
            JasperReport jsreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jsreport, null, conn);
            JasperViewer jv= new JasperViewer(jprint,false);
           JDialog dialog = new JDialog(this);//the owner
            dialog.setContentPane(jv.getContentPane());
            dialog.setSize(jv.getSize());
            dialog.setTitle("Danh sách");

            dialog.setVisible(true);
//            JasperViewer.viewReport(jprint);
//            JasperViewer.
        } catch (JRException ex) {
            Logger.getLogger(JasperRp.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained

    }//GEN-LAST:event_tableFocusGained

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased

    }//GEN-LAST:event_tableMouseReleased

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        new FormNguoiDung(this, true).setVisible(true);;
        cod.showResult(table);

    }//GEN-LAST:event_buttonThemActionPerformed

    private void tfIdStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdStuActionPerformed

    private void cbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhActionPerformed

    private void cbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSapXepActionPerformed

    private void cbChieuSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChieuSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChieuSapXepActionPerformed

    private void buttonXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXoa1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tfIdStu.setText("");
        tfNameStu.setText("");
        jDateNgaySinh1.setDate(null);
        jDateNgaySinh2.setDate(null);
        cbChieuSapXep.setSelectedIndex(0);
        cbGioiTinh.setSelectedIndex(0);
        cbSapXep.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLSinhVien dialog = new QLSinhVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JButton buttonXoa1;
    private javax.swing.JComboBox<String> cbChieuSapXep;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbSapXep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateNgaySinh1;
    private com.toedter.calendar.JDateChooser jDateNgaySinh2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfIdStu;
    private javax.swing.JTextField tfNameStu;
    // End of variables declaration//GEN-END:variables
private void paint_table() {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(60, 127, 177));
        table.getTableHeader().setForeground(new Color(255, 255, 255));
        table.setRowHeight(30);
        table.setShowGrid(true); // de the hien duong vien mac dich
        //table.setShowHorizontalLines(true);// de the hien duong vien ngang
        //table.setShowVerticalLines(true);// de the hien duong vien doc

    }

}
